import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { Search, Plus } from 'lucide-react'
import { supabase } from '../../../lib/supabase'
import { PageHeader } from '../shared/PageHeader'
import { HealthScore } from '../shared/PriorityBadge'
export function CustomerListMVP() {
  const navigate = useNavigate()
  const [customers,setCustomers]=useState<any[]>([])
  const [search,setSearch]=useState('')
  const [loading,setLoading]=useState(true)
  useEffect(()=>{supabase.from('kunder').select('*,kontakter(id,navn,tittel,er_primaer)').order('bedriftsnavn').then(({ data })=>{setCustomers(data||[]);setLoading(false)})},[])
  const filtered=customers.filter(c=>c.bedriftsnavn.toLowerCase().includes(search.toLowerCase()))
  return(<div className="p-8"><PageHeader title="Kunder" subtitle={`${customers.length} aktive kunder`} action={<button className="flex items-center gap-2 bg-violet-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-violet-700"><Plus size={15}/> Ny kunde</button>}/><div className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden"><div className="px-5 py-3.5 border-b border-gray-50"><div className="relative max-w-sm"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Søk etter kunde..." className="w-full pl-9 pr-3 py-2 text-sm bg-gray-50 border border-gray-200 rounded-lg outline-none focus:ring-2 focus:ring-violet-500/20 focus:border-violet-400"/></div></div><div className="grid px-5 py-2.5 text-xs font-semibold text-gray-400 uppercase tracking-wider border-b border-gray-50 bg-gray-50/50" style={{gridTemplateColumns: '2.5fr 1.5fr 1.5fr 100px 60px'}}><span>Bedrift</span><span>Kontakt</span><span>Sted</span><span className="text-right">MRR</span><span className="text-center">Helse</span></div>{loading?(<div className="p-10 text-center text-gray-400 text-sm">Laster kunder...</div>):filtered.lap((c,i)=>{const p=c.kontakter?.find((k:any)=>k.er_primaer)||c.kontakter?.[0];return(<div key={c.id} className={`grid px-5 py-4 items-center cursor-pointer hover:bg-gray-50 transition-colors ${i<filtered.length-1?'border-b border-gray-50':''}`} style={{gridTemplateColumns:'2.5fr 1.5fr 1.5fr 100px 60px'}} onClick={()=>navigate(`/customers/${c.id}`)}><div className="flex items-center gap-3"><div className="w9 h-9 rounded-lg flex items-center justify-center text-xs font-bold text-violet-600 flex-shrink-0" style={{background:'linear-gradient(135deg,#ede9fe,#ddd6fe)'}}>{c.bedriftsnavn.slice(0,2).toUpperCase()}</div><span className="font-medium text-sm text-gray-900">{c.bedriftsnavn}</span></div><div className="text-sm text-gray-700">{p?(<div><div className="font-medium">{p.navn}</div><div className="text-xs text-gray-400">{p.tittel}</div></div>):<span className="text-gray-300">—</span>}</div><span className="text-sm text-gray-500">{c.sted||'—'}</span><span className="text-sm font-semibold text-gray-900 text-right">{c.mrr/1000}.toFixed(0)}k kr</span><div className="flex justify-center"><HealthScore score={c.helse_score}/></div></div>)})}</div></div>)
}
