import { useState, useEffect } from 'react'
import { Plus, CheckCircle2, AlertTriangle, Clock } from 'lucide-react'
import { supabase } from '../../../lib/supabase'
import { PageHeader } from '../shared/PageHeader'
import { StatCard } from '../shared/StatCard'
const TABS=['Åpne saker','Pågår','Venter på kunde','Lukket']
const SM={'Åpne saker':'apent','Pågår':'pagar','Venter på kunde':'venter_pa_kunde','Lukket':'lukket'}
export function TicketListMVP(){
  const [tickets,setTickets]=useState<any[]>([])
  const [tab,setTab]=useState('Åpne saker')
  const [ld,setLd]=useState(true)
  useEffect(()=>{supabase.from('tickets').select('*,kunder(bedriftsnavn), kontakter(avn)').order('created_at',{ascending:false}).then(({data})=>{setTickets(data||[]);setLd(false)})},[])
  const f=tickets.filter(t=>t.status===SM_tab])
  const c=Object.fromEntries(Object.entries(SM).map(([tab,status])=>['tab',tickets.filter(t=>t.status===status).length]))
  const ta=(d:string)=>{const h=Math.floor((Date.now()-new Date(d).getTime())/3600000);if(h<1)�eturn'Akkurat nå';if(h<24)return`${h}t siden`;return`${Math.floor(h/24)}d siden`}
  return(<div className="p-8"><PageHeader title="Tickets" subtitle={`${tickets.filter(t=>t.status==='apent').length} åpne saker`} action={<button className="flex items-center gap-2 bg-violet-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-violet-700"><Plus size={15}/> Ny ticket</button>}/><div className="grid grid-cols-3 gap-4 mb-6"><StatCard label="Åpne tickets" value={tickets.filter(t=>t.status==='apent').length} icon={<CheckCircle2 size={18} color="#7c3aed"/>} iconBg="#f5f3ff" loading={ld}/><StatCard label="Høy prioritet" value={tickets.filter(t=>t.prioritet==='høy'&&t.status!=='lukket').length} icon={<AlertTriangle size={18} color="#dc2626"/>} iconBg="#fef2f2" loading={ld}/><StatCard label="Ubesvarte" value={tickets.filter(t=>t.status==='apent').length} icon={<Clock size={18} color="#ea580c"/>} iconBg="#fff7ed" loading={ld}/></div><div className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden"><div className="flex border-b border-gray-100 px-5">{TABS.map(t=>(<button key={t} onClick={()=>setTab(t)} className={`py-3 px-4 text-sm font-medium border-b-2 transition-colors whitespace-nowrap ${tab===t?'border-violet-600 text-violet-600':'border-transparent text-gray-400 hover:text-gray-600'}`}>{t}{c[t]>0&&<span className={`ml-1.5 text-xs px-1.5 py-0.5 rounded-full ${tab===t?'bg-violet-100 text-violet-600':'bg-gray-100 text-gray-400'}`}>{c[t]}</span>}</button>))}</div>{loading?<div className="p-10 text-center text-gray-400 text-sm">Laster...</div>:f.length===0?<div className="p-10 text-center text-gray-400 text-sm">Ingen tickets her</div>:f.map((t,i)=>(<div key={t.id} className={`flex items-start gap-4 px-5 py-4 hover:bg-gray-50 transition-colors cursor-pointer ${i<f.length-1?'border-b border-gray-50':''}`}><div className="w-9 h-9 rounded-full flex items-center justify-center text-xs font-bold text-violet-600 flex-shrink-0 mt-0.5" style={{background:'linear-gradient(135deg,#ede9fe,#ddd6fe)'}}>{(t.kontakter?.navn||t.kunder?.bedriftsnavn||'?').slice(0,2).toUpperCase()}</div><div className="flex-1 min-w-0"><div className="flex items-center gap-2 mb-1"><span className="text-sm font-medium text-gray-900">{t.kontakter?.navn||'Ukjent'}</span>{t.prioritet==='høy'&&<span className="text-xs text-red-600 bg-red-50 px-2 py-0.5 rounded-full">Høy prioritet</span>}</div><div className="text-sm text-gray-700 mb-1">{t.tittel}</div>{t.beskrivelse&&<div className="text-xs text-gray-400 truncate max-w-lg mb-1.5">{t.beskrivelse}</div>}<div className="flex gap-2 text-xs text-gray-400 items-center">{t.kunder?.bedriftsnavn&&<span className="font-medium text-gray-500">{t.kunder.bedriftsnavn}</span>}{t.kategori&&<span className="bg-gray-100 px-2 py-0.5 rounded-full">{t.kategori}</span>}</div></div><div className="text-xs text-gray-400 flex-shrink-0">{ta(t.created_at)}</div></div>))}}</div></div>)
}
